fix: failed to run custom build `gw-types`
error: failed to run custom build command for `gw-types v0.1.0 (/app/crates/types)`

Caused by:
  process didn't exit successfully: `/app/target/debug/build/gw-types-9e94f242bfcad04e/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'assertion failed: `(left == right)`
    left: `"0.6.1"`,
   right: `"0.7.2"`: unsatisfied molecule version', crates/types/build.rs:20:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed